# Generated by Django 5.2.6 on 2025-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertorio', '0002_repertorio_delete_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertorio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='repertorio/fotos'),
        ),
    ]
