# Generated by Django 5.2.6 on 2025-10-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertorio', '0002_filme_livro_serie_delete_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('estrela', models.SmallIntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')])),
                ('resenha', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série'), ('OUTRO', 'Outro')], default='FILME', help_text='Selecione se é um filme ou uma série.', max_length=5)),
                ('duracao', models.DurationField(blank=True, help_text="Duração do filme (ex: '01:45:00' para 1h 45m).", null=True)),
                ('temporada', models.PositiveSmallIntegerField(blank=True, help_text='Número da temporada (apenas se for série).', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
